// Available operations are separate from the permissions granted by default.
// Keep this catalog aligned with permission_available_actions() in settings.php.
export const permissionActions = [
  { key: "view", label: "View" },
  { key: "create", label: "Create" },
  { key: "edit", label: "Edit" },
  { key: "approve", label: "Approve" },
  { key: "reject", label: "Reject" },
  { key: "return", label: "Return for Revision" },
  { key: "submit", label: "Submit" },
  { key: "cancel", label: "Cancel" },
  { key: "archive", label: "Archive" },
  { key: "restore", label: "Restore" },
  { key: "import", label: "Import" },
  { key: "export", label: "Export" },
  { key: "print", label: "Print" },
  { key: "download", label: "Download" },
  { key: "upload", label: "Upload" },
  { key: "assign", label: "Assign KPI" },
  { key: "rate", label: "Rate" },
  { key: "generate", label: "Generate" },
  { key: "release", label: "Release Payment" },
  { key: "accept", label: "Accept" },
  { key: "nominate", label: "Nominate" },
  { key: "close", label: "Close Nominations" },
  { key: "reopen", label: "Reopen Nominations" },
  { key: "unlock", label: "Unlock Account" },
  { key: "backup", label: "Create Backup" },
];

export const moduleAvailableActions = {
  dashboard: ["view"],
  profile: ["view", "edit", "submit", "upload", "download", "print"],
  serviceRecord: ["view", "create", "edit", "import", "export", "print", "download", "submit", "upload"],
  users: ["view", "create", "edit", "archive", "restore"],
  permissions: ["view", "create", "edit", "approve", "reject"],
  settings: ["view", "create", "edit", "archive", "restore", "import", "export", "download", "upload", "backup", "unlock"],
  auditLogs: ["view"],
  calendar: ["view", "create", "edit"],
  employees: ["view", "create", "edit", "approve", "reject", "archive", "restore", "import", "export", "print", "download", "upload"],
  rewardsRecognition: ["view", "create", "edit", "archive", "restore", "print", "download", "export", "upload", "generate", "nominate", "close", "reopen"],
  promotions: ["view", "create", "edit", "approve", "reject", "cancel", "archive", "restore", "export", "print"],
  attendance: ["view", "create", "edit", "approve", "reject", "submit", "cancel", "archive", "restore", "import", "export", "print", "download"],
  leave: ["view", "create", "edit", "approve", "reject", "submit", "cancel", "accept", "archive", "restore", "export", "print", "download", "upload"],
  leaveBalance: ["view", "create", "edit", "import", "export"],
  payroll: ["view", "create", "edit", "approve", "reject", "return", "submit", "archive", "restore", "export", "print", "download", "upload", "generate", "release"],
  reports: ["view", "create", "edit", "assign", "rate", "submit", "archive", "restore", "upload", "export", "print", "download", "generate"],
  payslip: ["view", "generate", "export", "print", "download"],
};
